### ISSUE TITLE
 "export 'SimpleCrypt' was not found in 'ng2-simple-crypt'

### ISSUE THREAD

**Issue by munish29sharma** [dfa1234/ng2-simple-crypt#1]
while compiling, i am getting error:
 "export 'SimpleCrypt' was not found in 'ng2-simple-crypt'
does it work with angular 4 ?

**Comment by munish29sharma** [comment]
i had used "{ }" in the import, i removed that then it is working, can any body let me know why it has to used without "{ }"

**Comment by dfa1234** [comment]
I just updated the repo to be sure you can use it.
Everything is fine now, any version of angular is ok.
Instruction are on the readme.

**Comment by munish29sharma** [comment]
Thank you very much @dfa1234.
it is working now.
