### ISSUE TITLE
Angular 6 build fail when using this package. CLI indicate not appropriate code in index.ts

### ISSUE THREAD

**Issue by StudiosKelemy** [dfa1234/ng2-simple-crypt#2]
Angular 6 build fail when using this package. CLI indicate not appropriate code in index.ts

**Comment by dfa1234** [comment]
Thank to notify, I didn't expected Angular 6 to change anything. I check this.

**Comment by dfa1234** [comment]
Ok, I just made a test with the last cli and angular 6.0.0.
`ng serve` and `ng-build --prod` worked perfectly.
If you still have issues please post your dependencies and `ng --version`
